"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-2fac#wxx+bnur-ivb_^d1&&_*ofvl)^0g2ky83sgh#kf8hl#x$",
)

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    ""
).split(",")


# Render / reverse proxy HTTPS configuration
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "drf_spectacular",

    "apps.users",
    "apps.authentication",
    "apps.categories",
    "apps.service_requests",
    "apps.assignments",
    "apps.comments",
    "apps.attachments",
    "apps.notifications",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": (
            os.getenv("DB_NAME")
            or os.getenv("PGDATABASE", "neondb")
        ),

        "USER": (
            os.getenv("DB_USER")
            or os.getenv("PGUSER", "neondb_owner")
        ),

        "PASSWORD": (
            os.getenv("DB_PASSWORD")
            or os.getenv("PGPASSWORD")
        ),

        "HOST": (
            os.getenv("DB_HOST")
            or os.getenv("PGHOST")
        ),

        "PORT": os.getenv("DB_PORT", "5432"),

        "OPTIONS": {
            "sslmode": os.getenv(
                "PGSSLMODE",
                "require"
            ),
        },
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(
    BASE_DIR,
    "staticfiles"
)

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# WhiteNoise
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# EMAIL
# ============================================================

MAILERS = {
    "default": {
        "BACKEND": (
            "django.core.mail.backends.console.EmailBackend"
        ),
    },
}


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "users.User"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "DEFAULT_PAGINATION_CLASS": (
        "apps.users.pagination.StandardPagination"
    ),

    "PAGE_SIZE": 10,

    "DEFAULT_SCHEMA_CLASS": (
        "drf_spectacular.openapi.AutoSchema"
    ),
}


# ============================================================
# JWT
# ============================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=int(
            os.getenv(
                "JWT_ACCESS_TOKEN_LIFETIME_DAYS",
                "1"
            )
        ),
        minutes=int(
            os.getenv(
                "JWT_ACCESS_TOKEN_LIFETIME_MINUTES",
                "0"
            )
        ),
    ),

    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(
            os.getenv(
                "JWT_REFRESH_TOKEN_LIFETIME_DAYS",
                "7"
            )
        )
    ),

    "ROTATE_REFRESH_TOKENS": (
        os.getenv(
            "JWT_ROTATE_REFRESH_TOKENS",
            "True"
        ).lower() == "true"
    ),

    "BLACKLIST_AFTER_ROTATION": False,

    "UPDATE_LAST_LOGIN": True,

    "SIGNING_KEY": (
        os.getenv("JWT_SECRET_KEY")
        or os.getenv("SECRET_KEY")
        or SECRET_KEY
    ),

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),
}


# ============================================================
# DRF SPECTACULAR / SWAGGER
# ============================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Service Management API",

    "DESCRIPTION": (
        "Comprehensive API documentation for the "
        "Service Management system covering user "
        "authentication, service request lifecycle, "
        "staff assignments, comments, attachments, "
        "categories, and notifications."
    ),

    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": False,

    "COMPONENT_SPLIT_REQUEST": True,

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
}


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_URL = "/ui/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/ui/login/"


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SECURE_BROWSER_XSS_FILTER = True

    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),

        "script-src": (
            "'self'",
            "'unsafe-inline'",
        ),

        "style-src": (
            "'self'",
            "'unsafe-inline'",
        ),
    }