# Generated by Django 6.1 on 2026-09-09 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('service_requests', '0002_alter_servicerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Ticket Assignment', 'verbose_name_plural': 'Ticket Assignments'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(help_text='The manager or dispatcher who created this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(help_text='The technician responsible for resolving the ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='service_request',
            field=models.OneToOneField(help_text='The ticket allocated to a technician.', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='service_requests.servicerequest'),
        ),
    ]
