services:
  - type: web
    name: service-management-api
    runtime: python
    pythonVersion: 3.11
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: service-management-api
          property: host

  - type: postgres
    name: service-management-db
    plan: free
    ipAllowList: []
