# Generated by Django 6.1 on 2026-09-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_description_and_more'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(help_text='Primary category classifying the request.', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_number',
            field=models.CharField(db_index=True, editable=False, help_text='Format: SR-YYYY-NNNNNN', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
